In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
df = pd.read_csv('Titanic.csv', usecols = ['Cabin'])
df.head(5)

Cabin
0   NaN
1   C85
2   NaN
3  C123
4   NaN

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Cabin   204 non-null    object
dtypes: object(1)
memory usage: 7.1+ KB


In [45]:
df['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [58]:
df['Cabin_num'] = df['Cabin'].str.extract('(\d+)')
df['Cabin_cat'] = df['Cabin'].str[0]

In [59]:
df.head(5)

Cabin Cabin_num Cabin_cat
0   NaN       NaN       NaN
1   C85        85         C
2   NaN       NaN       NaN
3  C123       123         C
4   NaN       NaN       NaN

In [60]:
df['Cabin_cat'].unique()

array([nan, 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T'], dtype=object)

In [69]:
df['Cabin_cat'].fillna('Unavailable', inplace = True)

In [70]:
df['Cabin_num'].fillna('0').unique()

array([  0.,  85., 123.,  46.,   6., 103.,  56.,  23.,  78.,  33.,  30.,
        52.,  28.,  83.,  73.,  31.,   5.,  10.,  26., 110.,  58., 101.,
        69.,  47.,  86.,   2.,  19.,   7.,  49.,   4.,  32.,  80.,  36.,
        15.,  93.,  35.,  87.,  77.,  67.,  94., 125.,  99., 118.,  22.,
       106.,  65.,  54.,  57.,  34.,  18., 124.,  91.,  40., 128.,  37.,
        50.,  82.,  96.,  44., 104., 111.,  92.,  38.,  21.,  12.,  63.,
        14.,  20.,  79.,  25.,  95.,  39.,  70.,  16.,  68.,  41.,   9.,
        48., 126.,  71.,  51.,  62.,  24.,  90.,  45.,   8., 121.,  11.,
         3.,  17., 102.,  42., 148.])

In [71]:
df['Cabin_num'] = pd.to_numeric(df['Cabin_num'], errors = 'coerce', downcast = 'integer')

In [72]:
df['Cabin_num'].fillna(0).unique()

array([  0,  85, 123,  46,   6, 103,  56,  23,  78,  33,  30,  52,  28,
        83,  73,  31,   5,  10,  26, 110,  58, 101,  69,  47,  86,   2,
        19,   7,  49,   4,  32,  80,  36,  15,  93,  35,  87,  77,  67,
        94, 125,  99, 118,  22, 106,  65,  54,  57,  34,  18, 124,  91,
        40, 128,  37,  50,  82,  96,  44, 104, 111,  92,  38,  21,  12,
        63,  14,  20,  79,  25,  95,  39,  70,  16,  68,  41,   9,  48,
       126,  71,  51,  62,  24,  90,  45,   8, 121,  11,   3,  17, 102,
        42, 148], dtype=int16)

In [73]:
df['Cabin_num']

0        0
1       85
2        0
3      123
4        0
      ... 
886      0
887     42
888      0
889    148
890      0
Name: Cabin_num, Length: 891, dtype: int16

In [74]:
df['Cabin_num'].fillna(0, inplace = True)

In [75]:
df.head(5)

Cabin  Cabin_num    Cabin_cat
0   NaN          0  Unavailable
1   C85         85            C
2   NaN          0  Unavailable
3  C123        123            C
4   NaN          0  Unavailable